Currencies (module implementation, migrations, etc.)
vladislav-shkutovich/NestJS-Expenses-App pull request #2
Opened 2024-10-30 15:49 UTC by vladislav-shkutovich

// TODO: - Rebase branch from main after merge #1

2024-10-31 14:33 UTC, masontikhonov requested changes

2024-10-31 14:33 UTC, masontikhonov commented on .eslintrc.js
> +    '@typescript-eslint/no-var-requires': 'off',
Let's not disable this rule: no need for `require` in such modern project.

2024-10-31 14:33 UTC, masontikhonov commented on migrations/versioned/20241030152758-currencies-seed-collection.ts
> +    await collection.deleteMany({})
`down` can delete more docs than it was created in `up`, which is potentially harmful.
We have static list of currencies, and their codes are unique, so we can delete exactly what was created.

2024-10-31 14:33 UTC, masontikhonov commented on migrations/versioned/20241030152758-currencies-seed-collection.ts
> +import currencies from '../data/currencies.json'
Let's use more unique name so that it's bound to this particular migration, a la `20241030152758-currencies-seed-collection.data.json`.
It cannot be reused across migrations anyway.

2024-10-31 14:33 UTC, masontikhonov commented on migrations/versioned/20241030152827-currencies-create-index-code.ts
> +import { Db } from 'mongodb'
I would say we have to reorder migrations: first create indexes, then seed data. Otherwise, wrong data seeds (ie duplicated codes) may violate uniqueness constraint and block this migration.

2024-10-31 14:33 UTC, masontikhonov commented on src/currency/currency.controller.ts
> +  @Get(':code')
Why this change? It's against your API schema and tech implementation plan.

2024-10-31 14:33 UTC, masontikhonov commented on src/currency/currency.database.service.ts
> +    return currencies.map((currency) => currency.toObject())
Use of `lean` option here is more efficient. Currently we're fetching JSON, then converting it to instances of CurrencyModel, and immediately back to POJO. With lean redundant conversion to Model can be skipped.

2024-10-31 14:33 UTC, masontikhonov commented on src/currency/currency.database.service.ts
> +    return currencyByCode.toObject()
Here and elsewhere — consider use of `lean`

2024-10-31 14:33 UTC, masontikhonov commented on src/currency/dto/currency-param.dto.ts
> +  @Matches(/^[A-Za-z]{3}$/, {
Currency code can't be lowercased if you're using ISO 4217.
Overall, I would use `@IsISO4217CurrencyCode()` in this case.

2024-10-31 14:33 UTC, masontikhonov commented on src/currency/dto/currency-param.dto.ts
> +  @Transform(({ value }) => value.toUpperCase())
No need to transform, just do not accept lowercase as it's incorrect data (doesn't comply with ISO).

2024-10-31 14:33 UTC, masontikhonov commented on tsconfig.json
> +  "include": ["src", "types", "migrations"]
Let's discuss it in person

2024-11-01 10:34 UTC, vladislav-shkutovich commented on .eslintrc.js
> +    '@typescript-eslint/no-var-requires': 'off',
It was required to achieve a sync import from Umzug's `resolve` function:
```
const setupUmzug = (db: Db): Umzug<Db> => {
  return new Umzug({
    context: db,
    migrations: {
      glob: 'migrations/versioned/*.ts',
      resolve: ({ name, path, context }) => {
        if (!path) {
          throw new Error(`Failed to get path for migration ${name}`)
        }

        const migration = require(path).default

        return {
          name,
          up: () => migration.up({ context }),
          down: () => migration.down({ context }),
        }
      },
    },
    storage: new MongoDBStorage({
      collection: db.collection(MIGRATIONS_COLLECTION),
    }),
    logger: console,
  })
}
```
To get everything from export default in `const migration = require(path).default` line. The alternative and modern approach it to use a dynamic import like:
```
const migrationModule = await import(path)
const migration = migrationModule.default
```
But it's not accepted by Umzug's `resolve` signature, because it must be a sync function.

But (x2), I reworked it in a pretty simple way by using `module.exports` instead of `export default` in all migration files:
```
module.exports = {
  up: async ({ context }: { context: Db }) => {
    const collection = context.collection('currencies')
    await collection.insertMany(currencies)
  },
  down: async ({ context }: { context: Db }) => {
    const collection = context.collection('currencies')
    await collection.deleteMany({})
  },
}
```
So, the `resolve` function from Umzug setup is no longer needed at all:
```
const setupUmzug = (db: Db): Umzug<Db> => {
  return new Umzug({
    context: db,
    migrations: {
      glob: 'migrations/versioned/*.ts',
    },
    storage: new MongoDBStorage({
      collection: db.collection(MIGRATIONS_COLLECTION),
    }),
    logger: console,
  })
}
```
And it's working fine.

2024-11-01 10:46 UTC, vladislav-shkutovich commented on migrations/versioned/20241030152758-currencies-seed-collection.ts
> +    await collection.deleteMany({})
And it's a serious vulnerability, thanks!
Fixed:
```
down: async ({ context }: { context: Db }) => {
    const collection = context.collection('currencies')
    const codes = currencies.map((currency) => currency.code)
    await collection.deleteMany({ code: { $in: codes } })
  },
```

2024-11-01 10:49 UTC, vladislav-shkutovich commented on migrations/versioned/20241030152758-currencies-seed-collection.ts
> +import currencies from '../data/currencies.json'
Fixed as `20241101102849-currencies-seed-collection.data.json` instead of `currencies.json`.

2024-11-01 10:52 UTC, vladislav-shkutovich commented on migrations/versioned/20241030152827-currencies-create-index-code.ts
> +import { Db } from 'mongodb'
Agreed. It's a safer way.
Fixed and migrations restarted

2024-11-01 10:54 UTC, vladislav-shkutovich commented on src/currency/currency.controller.ts
> +  @Get(':code')
Let's discuss it in person on the next sync call

2024-11-01 11:15 UTC, vladislav-shkutovich commented on src/currency/currency.database.service.ts
> +    return currencies.map((currency) => currency.toObject())
Fixed here and in `UserDatabaseService`.

2024-11-01 11:16 UTC, vladislav-shkutovich commented on src/currency/currency.database.service.ts
> +    return currencyByCode.toObject()
Fixed

2024-11-01 11:20 UTC, vladislav-shkutovich commented on src/currency/dto/currency-param.dto.ts
> +  @Matches(/^[A-Za-z]{3}$/, {
Oh, it's much better than manual transformations, I missed this decorator somehow, thanks!

2024-11-01 11:20 UTC, vladislav-shkutovich commented on src/currency/dto/currency-param.dto.ts
> +  @Transform(({ value }) => value.toUpperCase())
Removed

2024-11-05 10:35 UTC, vladislav-shkutovich commented on src/currency/currency.controller.ts
> +  @Get(':code')
Fixed: now it's a single endpoint accepting optional query for multiple and single values like "?code=BYN,USD,EUR" or "?code=BYN".
```
export class CurrencyQueryParamsDto {
  @IsOptional()
  @Transform(({ value }) => value.split(',').map((v: string) => v.trim()))
  @IsArray()
  @IsString({ each: true })
  @IsISO4217CurrencyCode({ each: true })
  @IsUppercase({ each: true })
  code?: string[]
}

...

@Get()
  async getCurrencies(
    @Query() query: CurrencyQueryParamsDto,
  ): Promise<Currency[]> {
    return await this.currencyService.getCurrencies(query)
  }

...

  async getCurrencies(options: CurrencyQueryParamsDto): Promise<Currency[]> {
    const filter: FilterQuery<Currency> = {}

    if (options.code) {
      filter.code = { $in: options.code }
    }

    return await this.currencyModel.find(filter).lean()
  }
```

2024-11-05 15:49 UTC, vladislav-shkutovich commented on tsconfig.json
> +  "include": ["src", "types", "migrations"]
Reworked migrations as we discussed in [this commit](https://github.com/vladislav-shkutovich/NestJS-Expenses-App/pull/2/commits/2967b4459ed25e02353f1dd3b25d51d8f8473a93). It looks pretty simple now, when it's done, but it was in interesting battle 🤯
For migrations usage in Docker [just added one line](https://github.com/vladislav-shkutovich/NestJS-Expenses-App/pull/2/commits/9d5786495c4024fae6ed87b17f4568671b7405bf) to run them manually when it needed.

2024-11-06 16:49 UTC, masontikhonov approved these changes
Except for sync IO looks perfect!

2024-11-06 16:49 UTC, masontikhonov commented on migrations/2024.11.05T14.05.12.currencies-seed-collection.mjs
> +const currenciesJson = readFileSync(
Let's avoid sync IO as much as you can. `readFile` from `node:fs/promises` should work perfectly here.
Other way, is to try `import currencies from './path.json' with { type: 'json' }`.

2024-11-06 16:49 UTC, masontikhonov commented on migrations/scripts/migrator.mjs
> +  .finally(() => client.close())
`finally` will never be executed in case of error. You should define it _before_ catch in order to make it work both with resolve and rejection.

2024-11-06 16:49 UTC, masontikhonov commented on migrations/scripts/migrator.mjs
> +import { readFileSync } from 'node:fs'
Let's use async IO from `node:fs/promises`

2024-11-06 16:49 UTC, masontikhonov commented on package.json
> +    "migrate:up": "node migrations/scripts/migrator.mjs up",
Another approach if you need to map multiple commands, is to define only one script, for example:
```JSON
  "migrate": "./node migrations/scripts/migrator.mjs"
```
and then attach commands at launch:
```
yarn run migrate up
yarn run migrate down
```

2024-11-06 17:01 UTC, masontikhonov commented on migrations/scripts/migrator.mjs
> +umzug
Why mixing top-level await and `.catch....` chain?

2024-11-13 09:09 UTC, vladislav-shkutovich commented on migrations/2024.11.05T14.05.12.currencies-seed-collection.mjs
> +const currenciesJson = readFileSync(
Agreed, my bad.
Now, using ESM, `import currencies from './path.json' with { type: 'json' }` works and it looks simpliest here. Seems like it's an experimental feature, but it works.
![image](https://github.com/user-attachments/assets/14a11018-0c04-4e9e-a47c-f095607529fc)

2024-11-13 09:21 UTC, vladislav-shkutovich commented on migrations/scripts/migrator.mjs
> +  .finally(() => client.close())
Fixed:
```
umzug
  .runAsCLI()
  .finally(() => client.close())
  .catch((err) => {
    console.error('Migration failed:', err)
    process.exit(1)
  })
```
I didn't know that `finally` could be used not only at the end of a promise chain. Caught in the "naming" trap 😅

2024-11-13 09:22 UTC, vladislav-shkutovich commented on migrations/scripts/migrator.mjs
> +import { readFileSync } from 'node:fs'
Fixed `import { readFile } from 'node:fs/promises'`

2024-11-13 09:30 UTC, vladislav-shkutovich commented on package.json
> +    "migrate:up": "node migrations/scripts/migrator.mjs up",
Fixed and readme.md migrations guide updated too.

2024-11-13 09:32 UTC, vladislav-shkutovich commented on migrations/scripts/migrator.mjs
> +const getDatabaseClient = async (uri) => {
Fixed

2024-11-13 10:02 UTC, vladislav-shkutovich commented on migrations/scripts/migrator.mjs
> +const setupUmzug = async () => {
Fixed

2024-11-13 10:23 UTC, vladislav-shkutovich commented on migrations/scripts/migrator.mjs
> +umzug
Previous file variant:
```
import { MongoClient } from 'mongodb'
import { MongoDBStorage, Umzug } from 'umzug'
import { readFileSync } from 'node:fs'

const MONGODB_URI = process.env.MONGODB_URI
const MIGRATIONS_COLLECTION = 'migrations'

if (!MONGODB_URI) {
  console.error(
    'MONGODB_URI was not provided by the CLI params. Please make sure you provide this variable (example: MONGODB_URI="your_uri" yarn <migration-command>)',
  )
  process.exit(1)
}

const getDatabaseClient = async (uri) => {
  const client = new MongoClient(uri)
  await client.connect()
  return client
}

const setupUmzug = async () => {
  const client = await getDatabaseClient(MONGODB_URI)
  const db = client.db()

  const umzug = new Umzug({
    context: db,
    migrations: {
      glob: 'migrations/*.mjs',
    },
    create: {
      template: (filepath) => [
        [
          filepath,
          readFileSync(
            'migrations/templates/migration.template.mjs',
          ).toString(),
        ],
      ],
    },
    storage: new MongoDBStorage({
      collection: db.collection(MIGRATIONS_COLLECTION),
    }),
    logger: console,
  })

  return { umzug, client }
}

const { umzug, client } = await setupUmzug()

umzug
  .runAsCLI()
  .catch((err) => {
    console.error('Migration failed:', err)
    process.exit(1)
  })
  .finally(() => client.close())
```
And now it looks like this:
```
import { MongoClient } from 'mongodb'
import { MongoDBStorage, Umzug } from 'umzug'
import { readFileSync } from 'node:fs'

const MONGODB_URI = process.env.MONGODB_URI
const MIGRATIONS_COLLECTION = 'migrations'

if (!MONGODB_URI) {
  console.error(
    'MONGODB_URI was not provided by the CLI params. Please make sure you provide this variable (example: MONGODB_URI="your_uri" yarn <migration-command>)',
  )
  process.exit(1)
}

const client = new MongoClient(MONGODB_URI)

let exitCode = 0
try {
  await client.connect()
  const db = client.db()

  const umzug = new Umzug({
    context: db,
    migrations: {
      glob: 'migrations/*.mjs',
    },
    create: {
      template: (filepath) => [
        [
          filepath,
          readFileSync(
            'migrations/templates/migration.template.mjs',
          ).toString(),
        ],
      ],
    },
    storage: new MongoDBStorage({
      collection: db.collection(MIGRATIONS_COLLECTION),
    }),
    logger: console,
  })

  await umzug.runAsCLI()
} catch (err) {
  exitCode = 1
  console.error('Migration failed:', err)
} finally {
  await client.close()
}

process.exit(exitCode)
```
The process will be terminated with an implicitly defined code as before, but all commands like `client.close()` will be executed anyway.

2024-11-13 10:30 UTC, vladislav-shkutovich commented
@masontikhonov
Recent code review remarks (after approval) were eliminated [here](https://github.com/vladislav-shkutovich/NestJS-Expenses-App/pull/2/commits/0697e28891f5a07756e4e9e6616afb7a6c05cf30). You can check only this commit to save time reviewing entire PR again.

2024-11-13 11:45 UTC, masontikhonov commented on migrations/scripts/migrator.mjs
> +import { readFileSync } from 'node:fs'
I pretty much sure that I was using async `template` in my previous work with `umzug`:
```JS
	create: {
		folder: resolve(__dirname, './schema'),
		template: async (filepath) => {
			return [
				[
					filepath,
					await readFile(
						resolve(__dirname, './templates/schema-migration-template.js'),
						{ encoding: 'utf8' },
					),
				],
			];
		},
	},
```

2024-11-13 12:31 UTC, vladislav-shkutovich commented on migrations/scripts/migrator.mjs
> +import { readFileSync } from 'node:fs'
My bad. I forgot about `resolve` method in `readFile` method. [Fixed](https://github.com/vladislav-shkutovich/NestJS-Expenses-App/pull/2/commits/606a8903323beb7bc23ce01c9c9b20ca727bc027)

2024-11-13 12:56 UTC, merged